# HeySam call data — auto-refreshed 2026-05-19
# Most recent meeting per customer (fetched via HeySam MCP)

HEYSAM_CALLS = {
    "ROCK ON TRUCKS": {
        "bot_id": "141769d4-5a40-474c-ae88-97af13f8a371",
        "date": "May 15",
        "title": "Demo: New Rates Experience",
        "overall": "positive",
        "key_topics": "New dynamic rate card walkthrough — rates set at project level, matched at job/dispatch level. Equipment type gaps (quad/quint axle missing). Rate change propagation to open orders. Need for 'middle state' billing (completed-but-not-invoiced orders). Monday rate increase ($4.50→$5.50 fuel surcharge). CA state tax not visible on invoices.",
        "challenges": "New rate card not yet live (small bugs). 'Middle state' billing not yet built — critical for daily workflow. Manual rate updates per order persist until then. Quad/quint axle types missing from equipment list. CA tax visibility gap on invoices/receivables.",
        "url": "https://app.heysam.ai/calls/141769d4-5a40-474c-ae88-97af13f8a371",
    },
    "RONYX LOGISTICS LLC": {
        "bot_id": "1a111719-028e-4a4c-936b-76aa4e492f2f",
        "date": "May 15",
        "title": "Ronyx FSC jobs by the hour",
        "overall": "positive",
        "key_topics": "Fuel surcharge feature demo for Pro Ag contract. 2% surcharge per $0.10 fuel price exceeds $4/gallon (based on weekly commodities index). Full FSC setup walkthrough — fuel price index, threshold schedule, add-on at project/job level. Test run on driver Juan ('Johnny Jeep') planned. Pro Ag contract >100 trucks.",
        "challenges": "Fuel surcharge calculation method unclear (18% vs 36%) — pending clarification from Stephanie Spiro (Pro Ag). Contract with Pro Ag still being renegotiated. Manual weekly fuel price index updates required. Customer self-identifies as not very tech-savvy.",
        "url": "https://app.heysam.ai/calls/1a111719-028e-4a4c-936b-76aa4e492f2f",
    },
    "DUFFERIN AGGREGATES (CRH)": {
        "bot_id": "ae22ed42-028d-48a6-9d08-779fed56f3c2",
        "date": "May 18",
        "title": "Kyle Gear <> Tim (Tread)",
        "overall": "positive",
        "key_topics": "Live platform demo for Kyle Gear (VP/GM, CRH) using PJ Keating and Tilcon accounts — Kyle acknowledged significant product improvement since 1-2 years ago. Potential pilot: inbound ag hauls or plant-to-plant moves (~10 trucks, 1 job). Carrier rate cards and vendor-specific pricing confirmed. Driver pay Vista integration already live at Tilcon/PJ Keating. FleetWatcher gap: 65-70% CRH volume is brokered with no driver-level visibility. Craig (VPGM Concrete West, Lutz) identified as key internal champion.",
        "challenges": "Hauler/app fatigue — CRH haulers frustrated by multiple RFP and app adoption requests. Kevin Price's stance: pilot with someone else before replacing FleetWatcher. Kyle needs to socialize internally before formal pilot. Marine terminal congestion reducing Tampa loads (~5/day → ~2/day).",
        "url": "https://app.heysam.ai/calls/ae22ed42-028d-48a6-9d08-779fed56f3c2",
    },
    "R.W. DUNTEMAN CO.": {
        "bot_id": "83a7e050-af7b-4466-b487-f0f41fd96614",
        "date": "May 14",
        "title": "RW Dunteman Vendor Settlement",
        "overall": "positive",
        "key_topics": "End-to-end payables/settlement walkthrough using live data (job 2407, Mena Trucking). Bulk create settlement, void/correct, approve/paid workflow confirmed. Vista ERP integration on hold until Tim returns. Driver phase code selection feature (can be enabled). Two-way messaging request from Brett.",
        "challenges": "Vista ERP export not yet active — delays full billing automation. Drivers cannot add job-level notes (only load-level) — creates manual reconciliation. Two-way messaging not live. Manual hour splitting across multiple orders per day.",
        "url": "https://app.heysam.ai/calls/83a7e050-af7b-4466-b487-f0f41fd96614",
    },
    "DANIELA TRUCKING & GRADING": {
        "bot_id": "cfcc94ee-500b-48aa-a7e5-1316050617b7",
        "date": "May 13",
        "title": "Daniela <> Tread",
        "overall": "neutral",
        "key_topics": "Account recovery call (Sameer + Amy). Truck tracking fix (feature flag enabled). Geofence/cycle time reporting built and committed. Customer portal demoed live — team was unaware it existed. CSV/QuickBooks fix (load cap 'running' toggle). API integration interest — Dwayne building customer ordering app. Loader/scales integration interest.",
        "challenges": "HIGH CHURN RISK — actively evaluating 2 competitors. Trust deficit from multiple incorrect support responses ('that feature doesn't exist'). CSV/QuickBooks requires manual intervention per order (4-5 month unresolved issue). Offline GPS gaps in FL. Multiple materials per load is a system limitation.",
        "url": "https://app.heysam.ai/calls/cfcc94ee-500b-48aa-a7e5-1316050617b7",
    },
    "NATIONAL LIME AND STONE": {
        "bot_id": "6bfb7ac7-5adc-4090-b45a-0ed5e77b3340",
        "date": "May 13",
        "title": "TREAD - Order or Project Discussion",
        "overall": "positive",
        "key_topics": "API integration technical groundwork with Christopher Harn (developer). Projects vs orders clarified — aggregate side uses orders only; asphalt/paving uses projects (WEM scale integration went live). Truck/hauler master data strategy (paid haulers 1-500 as primary universe). Chris Harn site visits Canton (May 28) and Cary (May 29).",
        "challenges": "Truck ID uniqueness across sites — same truck may have different numbers at different plants. Non-paid hauler edge cases need mapping. Master data must be pre-loaded via CRUD APIs (cannot auto-create through order importer). Manual data entry continues until integration live.",
        "url": "https://app.heysam.ai/calls/6bfb7ac7-5adc-4090-b45a-0ed5e77b3340",
    },
    "4M TRUCKING": {
        "bot_id": "67b47053-e174-452d-9c00-9ebbae8e1382",
        "date": "May 13",
        "title": "4M recurring check in",
        "overall": "negative",
        "key_topics": "Missing customer rates on orders (rates dropped via order copy chain). Fuel surcharge not auto-updating (regression from 'restore jobs' feature). Order timeline incorrectly attributing truck count changes to Lonie. Copy & Edit vs Edit UX confusion causing accidental overwrites. Rate system revamp in engineering.",
        "challenges": "HIGH CHURN RISK — Lonie explicitly stated 4M is actively evaluating alternatives. Settlements on hold due to rate reliability. Fuel surcharge bug requires manual approve/unapprove workaround per job. Audit log inaccuracies undermine trust. Rate system issues persisting 4-5 months.",
        "url": "https://app.heysam.ai/calls/67b47053-e174-452d-9c00-9ebbae8e1382",
    },
    "VOLKER STEVIN CONTRACTING": {
        "bot_id": "ec585185-cd2c-4734-af84-a902274727c4",
        "date": "May 13",
        "title": "tread / volkerstevin",
        "overall": "positive",
        "key_topics": "New dispatcher Sameer Bhalla onboarding walkthrough — full dispatch platform training. PO/VSC number workflow and edge cases. Vendor onboarding meeting next morning (Adi from Teresano anxious). D365 ERP integration — POs push from Microsoft D365. GPS tracking, approvals, weather hold. Sandbox practice before go-live.",
        "challenges": "Adi from Teresano called Sameer in a panic about the platform — needs careful handling at vendor meeting. One-way messaging only (no driver response capability). Mobile app lacks truck count indicators (vs web app). PO/VSC workflow edge cases need Gemma's input.",
        "url": "https://app.heysam.ai/calls/ec585185-cd2c-4734-af84-a902274727c4",
    },
    "BUESING CORP": {
        "bot_id": "fa98448a-93a8-469c-a50f-0f581671b320",
        "date": "May 11",
        "title": "AR Testing (feedback)",
        "overall": "positive",
        "key_topics": "Bulk PDF upload feature (in development) — Tyler currently splits PDFs manually one by one. Ghost/dummy truck accounts for brokers not in Tread. Hourly billing configuration via freight rate settings. Tyler gradually migrating more drivers into Tread.",
        "challenges": "Bulk PDF upload not yet available — soft deadline of end of May before summer busy season. Broker workarounds (dummy accounts) add complexity. Ticket approval requirement for AR CSV export still needs verification.",
        "url": "https://app.heysam.ai/calls/fa98448a-93a8-469c-a50f-0f581671b320",
    },
    "GEORGE J. IGEL & CO.": {
        "bot_id": "2593d1c6-ea4d-4e62-8a69-b1b0d9660bff",
        "date": "May 11",
        "title": "George Igel <> Tread",
        "overall": "positive",
        "key_topics": "Admin setup + project/order dispatch + time approval onboarding (Tim Chung). Mixed per-ton/per-hour rates on same project — rate mapping by material type feature coming in ~2 weeks. ~40 vendors (30+ multi-truck brokers) to onboard. Fuel surcharge scheduling via dynamic index. Phase code setup. Amy and Christophe joined as observers.",
        "challenges": "Mixed rate types on same project not yet fully supported (feature coming). Phase code switching mid-day requires manual reconciliation. Vendor onboarding scale — 40 vendors, premature invite emails a risk. Ellie (main dispatcher) not yet onboarded.",
        "url": "https://app.heysam.ai/calls/2593d1c6-ea4d-4e62-8a69-b1b0d9660bff",
    },
    "AMRIZE: NCR-TWIN CITIES": {
        "bot_id": "9c63298e-eb0f-49dc-940b-603c2841438f",
        "date": "May 11",
        "title": "Amrize SW - Dispatch Review",
        "overall": "neutral",
        "key_topics": "Hands-on dispatch onboarding (Marco + Tim Chung). Vendor pool setup and bulk assignment workflow. Apex replication issue — tomorrow's orders not appearing in Tread. All orders showing vehicles=1 due to dispatcher data entry error in Apex. Vendor import Google Sheet cleanup. June 1 go-live target.",
        "challenges": "CRITICAL: Tomorrow's orders not in Tread — Apex replication issue is a go-live blocker. All orders coming in as vehicles=1 (dispatch team retraining needed). Incomplete vendor list. June 1 deadline set by absent stakeholder — alignment gap.",
        "url": "https://app.heysam.ai/calls/9c63298e-eb0f-49dc-940b-603c2841438f",
    },
    "TILCON CT INC": {
        "bot_id": "da5fe81e-768f-4134-92ce-2e7010c409f1",
        "date": "May 12",
        "title": "Tilcon <> Tread Check-in",
        "overall": "neutral",
        "key_topics": "Milling equipment type always maps to pickup locations (fix). Construction performance report updated (exclude job types 9+). Superintendent access concerns — risk of accidental edits. Josh Novak job visibility issue (traced to Larry Chamberlain's retired name in Apex). Truck count reversion bug. Apex address/site sync rules. Upcoming idle time + cycle time metrics.",
        "challenges": "No read-only dispatcher view — superintendents risk accidental edits. Larry Chamberlain (retired) still in Apex causing foreman assignment errors. Address/site updates from Apex don't sync to Tread (locked integration rules). Foreman onboarding still incomplete.",
        "url": "https://app.heysam.ai/calls/da5fe81e-768f-4134-92ce-2e7010c409f1",
    },
    "STATEWIDE MATERIALS": {
        "bot_id": "a400077c-d4ac-45af-ac88-e131e0e7028d",
        "date": "May 7",
        "title": "Statewide <> Tread Weekly",
        "overall": "neutral",
        "key_topics": "Implementation status update. Vendor/customer data cleanup on hold pending month-end close. Truck data upload in progress (TR numbers, OO flags). Projects export report complete (Sage columns). CSV/Sage settlement export upcoming feature. Vendor deactivate/reactivate on roadmap.",
        "challenges": "Data cleanup blocked by month-end close. Vendor deactivate/reactivate feature not yet available — key workflow gap. Test order dependent on Liz availability.",
        "url": "https://app.heysam.ai/calls/a400077c-d4ac-45af-ac88-e131e0e7028d",
    },
    "THUNDERBOLT": {
        "bot_id": "11129f6a-8f14-43b8-bf97-c26eab9082c4",
        "date": "May 7",
        "title": "Thunderbolt - Tread: Project Data Review",
        "overall": "positive",
        "key_topics": "Onboarding — project data configuration. Duplicate PO number workaround (letter suffixes: 23-316-C, 23-316-CA). Site upload and geofence configuration (500m radius, 180s dwell). New user accounts setup. Follow-up session with PM team scheduled for next week.",
        "challenges": "Duplicate PO numbers required manual workaround — potential confusion for PM team. Site upload and geofence homework still pending. PM team must make final decisions on naming conventions before go-live.",
        "url": "https://app.heysam.ai/calls/11129f6a-8f14-43b8-bf97-c26eab9082c4",
    },
    "TOMLINSON": {
        "bot_id": "adde2eb4-8fee-4cbc-b632-038b7876667b",
        "date": "May 7",
        "title": "TREAD: Bi-Weekly Updates",
        "overall": "positive",
        "key_topics": "Progress review on issue tracker. Copy & Edit fix confirmed. Counter badge fix confirmed. VPN blocking SSO (Rafael whitelisting domains). WBS/phase code fix pending release. New Roles feature in engineering queue (mid-month). Idle Time + Cycle Time per-load metrics upcoming. Mobile foreman dashboard request.",
        "challenges": "VPN blocking SSO — domain whitelisting still in progress. WBS/phase code intermittent bug (fix not yet released). New Roles feature delayed. Mobile app UX gaps — foremen must click through multiple screens for job-level data.",
        "url": "https://app.heysam.ai/calls/adde2eb4-8fee-4cbc-b632-038b7876667b",
    },
    "WERDCO BC INC.": {
        "bot_id": "b5615b81-9988-485e-83ce-59f16c200079",
        "date": "May 7",
        "title": "Werdco <> TREAD QuickBooks Desktop Integration",
        "overall": "neutral",
        "key_topics": "QB Desktop integration testing delayed — Jen unavailable for 2 weeks (payroll system implementation). Next week repurposed for roadmap demo + feature walkthrough. Northern Nevada (NDX) drop as candidate test job. Duplicate job feature on roadmap.",
        "challenges": "Jen unavailable delays integration testing milestone. Brandon's availability limited as operations pick up. No confirmed test job yet. Duplicate job feature not yet available.",
        "url": "https://app.heysam.ai/calls/b5615b81-9988-485e-83ce-59f16c200079",
    },
    "TAPANI INC": {
        "bot_id": "11d60a1a-43cd-459d-9dbd-e665f3c0b952",
        "date": "May 7",
        "title": "30 min with Latefa (Brady Kysar)",
        "overall": "neutral",
        "key_topics": "Reporting issues: dashboard report missing ticket number column vs emailed report. Fix agreed — add ticket number column to dashboard report. PDF/PNG export truncation bug (only first page renders). Internal notes feature on approvals page — in development, video update coming.",
        "challenges": "PDF/PNG export only captures first page — engineering ticket needed. Some foremen may not be receiving daily reports (under investigation). Internal notes feature request was not yet assigned to product team.",
        "url": "https://app.heysam.ai/calls/11d60a1a-43cd-459d-9dbd-e665f3c0b952",
    },
    "WALKER AG GROUP": {
        "bot_id": "f2b8e120-0397-4a7b-9b79-65d487b7ea27",
        "date": "May 6",
        "title": "Walker Ag <> Tread Training",
        "overall": "positive",
        "key_topics": "Onboarding session — Sullivan project setup. Vendor setup (5-6 vendors, already on board). Dispatch workflow, copy-and-edit for multiple pickup sites. Geofence set to 1,500 ft. Scale ticket approvals replacing manual spreadsheet. Fuel surcharge configuration (trucking + materials) deferred to follow-up. ~100 trucks daily across multiple sites.",
        "challenges": "Fuel surcharge complexity (fluctuation-based for both trucking + materials — follow-up needed). Quad equipment type not natively in system. Vendor training on mobile ticket submission over 2-3 weeks. Beth and Sam (approvers) not yet onboarded.",
        "url": "https://app.heysam.ai/calls/f2b8e120-0397-4a7b-9b79-65d487b7ea27",
    },
    "PRIME AGGREGATE TRANSPORTATION": {
        "bot_id": "f9af8bf6-c848-40e9-b701-3c00d3b7d213",
        "date": "May 18",
        "title": "Prime Aggregates <> Tread Training - Q&A",
        "overall": "positive",
        "key_topics": "Hands-on onboarding session with Adam Holst (owner), Rosa (dispatcher), Lindsay (billing). Vendor/driver type setup: owner operators, multi-truck OOs, brokers — Legacy Haulers and Victor Gonzalez set up as live test accounts. Test order dispatched to Victor during call. ~203 vendors to bulk import once clean list provided. HaulWare integration discussed (CSV export option, decision pending on ticket vs. AP voucher level). Commission/add-on pay rate setup covered.",
        "challenges": "Driver list previously sent was incomplete and unclean — delaying bulk import. Implementation bottleneck on Adam (limited bandwidth); intern now hired to assist. HaulWare import level decision still pending. Victor Gonzalez hasn't installed Tread driver app yet. Multi-truck broker dispatch method needs decision before setup.",
        "url": "https://app.heysam.ai/calls/f9af8bf6-c848-40e9-b701-3c00d3b7d213",
    },
    "CANTON CONCRETE (DUPLICATE)": {
        "bot_id": "6354c438-da88-4d88-8c81-1793b3c11daf",
        "date": "May 18",
        "title": "Canton Concrete <> Tread Billing Questions",
        "overall": "positive",
        "key_topics": "Lucretia (ops/office manager) walkthrough of invoice-to-settlement workflow by driver/truck and date range — replacing manual paper logs and calculator. Driver setup confusion resolved (owner-operator vs. company driver — same functionality). 87% driver acceptance rate. Monthly fuel surcharge editing confirmed in-platform. QuickBooks Desktop (Enterprise) integration interest noted. New general billing report (payables + receivables) in development.",
        "challenges": "QuickBooks Desktop integration not yet available — no timeline confirmed, slowing full workflow replacement. New billing report still in development. One driver has location permissions permanently denied. Older drivers slower to adopt platform.",
        "url": "https://app.heysam.ai/calls/6354c438-da88-4d88-8c81-1793b3c11daf",
    },
    "N.S. TRUCKING INC.": {
        "bot_id": "9cb4ceb5-6e81-4403-982c-b2a9e94c881c",
        "date": "May 6",
        "title": "NS Trucking Check in",
        "overall": "positive",
        "key_topics": "Settlement truck number discrepancies — trucks 690, 577, 708 (681). Void and recreate settlement workflow demonstrated. Root cause: dispatch (Josh) sending jobs to vendor instead of driver accounts; no equipment set on jobs. Truck 690 had 3-week activity gap (Mar 30–Apr 21). Latefa introduced as new primary CSM.",
        "challenges": "Dispatch (Josh) incorrectly assigning truck numbers / sending jobs to vendor not driver — creates systematic settlement errors. Truck 690 (Ernesto) 3-week activity gap indicates inconsistent platform usage. Settlement corrections are time-consuming.",
        "url": "https://app.heysam.ai/calls/9cb4ceb5-6e81-4403-982c-b2a9e94c881c",
    },
    "IMPACT SAND & GRAVEL": {
        "bot_id": "d11d95ec-f8f3-4b68-b5c4-5e7e43a5a591",
        "date": "May 15",
        "title": "Contract review - Impact Sand and Gravel",
        "overall": "positive",
        "key_topics": "1-year contract agreed — monthly billing, $3,750 implementation fee. Owner Bill Wadley on 10-day vacation; operations contact Ning Xiang delegated to proceed. Fastway integration gap discussed (not yet supported). Pricing complexity and beta concerns addressed. Sales rep Tutt led call.",
        "challenges": "Fastway integration not yet available — potential friction at go-live. Bill Wadley (owner/signatory) unavailable for 10 days. Beta concerns raised. Pricing structure complexity acknowledged.",
        "url": "https://app.heysam.ai/calls/d11d95ec-f8f3-4b68-b5c4-5e7e43a5a591",
    },
    "LEAH TRUCKING": {
        "bot_id": "a3afbff1-5b1a-4e6d-a8c4-7f2b9d3e1c04",
        "date": "May 14",
        "title": "Leah Trucking | Tread Demonstration",
        "overall": "positive",
        "key_topics": "~90 trucks daily, 70+ sub-haulers in Orange, TX. Dispatch manager (Uni Trucking LLC, replaced Veronica Oct 2025) attended demo with Will Amen (sales). AI ticket scanning and Axon accounting integration both high interest. Sub-hauler management workflow reviewed.",
        "challenges": "Owner Mr. George not yet engaged — deal not closed. Owner buy-in required before contract. Axon accounting integration availability unclear.",
        "url": "https://app.heysam.ai/calls/a3afbff1-5b1a-4e6d-a8c4-7f2b9d3e1c04",
    },
}
