QUO_CALLS = {
    "ALLIANCE INDUSTRIES": [
        {
            "id": "369588743913",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 108,
            "contact": "Mark",
            "summary": "Jill from TRED called Mark to confirm additional information for his account setup. Mark is the owner of Alliance Industries LLC and has two trucks with drivers. Mark is returning to TRED after a hiatus but has been with Tilcon for twenty years. Jill will create the account and send Mark an SMS invitation to log in once it's ready",
            "next_steps": "Jill to create Mark's account in the TRED system.. Jill to send an SMS invitation to Mark once the account is ready.. Mark to wait for the SMS to log in to TRED",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CN17d6ba3317894f11aee92580f9342645",
        },
    ],
    "BRETT CLARK COMPANY": [
        {
            "id": "369400996579",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 68,
            "contact": "Brett Clark",
            "summary": "Brad inquires about communication with vendors through order notes. Marco confirms that vendors can see order notes but not internal or project notes. The conversation clarifies what types of notes are visible to vendors",
            "next_steps": "Ensure that vendors are aware of the order notes they can access.. Consider discussing with the team the importance of using the correct notes for communication.. Follow up with any additional questions regarding the note system",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNf6a94e767c4d4251a1190b73a6ce4fba",
        },
        {
            "id": "369067369178",
            "date": "2026-05-11",
            "direction": "inbound",
            "duration_sec": 144,
            "contact": "Brett Clark",
            "summary": "Brett contacted Marco regarding Eno, Inc., a sub hauler. Brett mentioned that Eno did not receive an invite sent by Marco. Marco agreed to resend the invite to the correct email address for Dennis at Eno. Brett corrected the spelling of the name and provided the proper email address. Marco explained how to send an invite through the system. Brett confirmed that he would change the time zone to Central Standard Time",
            "next_steps": "Marco to resend the invite to Dennis at dennis@eno-inc.com.. Brett to change the time zone to Central Standard Time in the system.. Brett to ensure the invite is sent via text to Joe and email to Dennis",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNf6a94e767c4d4251a1190b73a6ce4fba",
        },
    ],
    "DUFFERIN AGGREGATES (CRH)": [
        {
            "id": "369213482688",
            "date": "2026-05-12",
            "direction": "inbound",
            "duration_sec": 50,
            "contact": "Hailey (CRH",
            "summary": "Hailey from Dufferin requested the Tread ID for Gill and Company. Marco provided the Tread ID: 069 Charlie82. The conversation was brief and ended amicably",
            "next_steps": "Ensure the Tread ID is documented for future reference.. Follow up with any additional needs from Hailey or Dufferin",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNdc73726058f744aa9ff2a7d422184a9d",
        },
        {
            "id": "369081981627",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 641,
            "contact": "Hailey (CRH",
            "summary": "Hailey is trying to set up a new driver but encounters an issue with the driver's phone number being linked to an existing account. Marco identifies a potential typo in the phone number that is causing the issue. Marco confirms that the new driver is enrolled with the same company, Farmers Pride, and has removed the conflicting account to allow for re-entry. Hailey is experiencing another error related to a truck being invalid when trying to create a new order for CRH Dufferin. Marco suggests that Hailey cancel the current order and set it up under Dufferin Construction for better compatibility",
            "next_steps": "Hailey will cancel the current order from the CRH Dufferin account.. Hailey will create a new order under the Dufferin Construction account.. Marco will monitor the situation to ensure no further issues arise with the driver's setup",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNdc73726058f744aa9ff2a7d422184a9d",
        },
        {
            "id": "369051380457",
            "date": "2026-05-11",
            "direction": "inbound",
            "duration_sec": 34,
            "contact": "Hailey (CRH",
            "summary": "Marco Alvarez provided a Tread ID for the trucking company Bell CT upon request. The Tread ID given was 'CAsInCharlie, 91 8AForAlphaAForAlpha'. The conversation was brief and concluded with polite farewells",
            "next_steps": "Confirm receipt of the Tread ID with the requester.. Ensure the Tread ID is documented for future reference.. Follow up if any additional information is needed regarding Bell CT",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNdc73726058f744aa9ff2a7d422184a9d",
        },
    ],
    "FLH LOGISTICS LLC": [
        {
            "id": "369365520117",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 90,
            "contact": "Freddie",
            "summary": "Jill from Trag contacted Fredia to activate her account. Fredia confirmed she is the owner and driver of FLH Logistics LLC. Jill confirmed the truck type as pneumatic for truck number 95008. Jill will create the account and send an SMS invitation for Fredia to log in to the Tread app",
            "next_steps": "Create the account for FLH Logistics LLC.. Send an SMS invitation to Fredia for Tread app login",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN8cf2598845484562aec38a3265e2c9da",
        },
    ],
    "FRANKIE TRUCKING": [
        {
            "id": "369035013839",
            "date": "2026-05-11",
            "direction": "inbound",
            "duration_sec": 152,
            "contact": "Juan",
            "summary": "Jill Bajenting answered a call regarding messaging issues with the app. The caller, associated with Frankie Trucking, reported not receiving job messages. Jill clarified that no jobs had been sent to the caller and advised contacting their dispatcher. The caller acknowledged that the issue was with their company, not the app",
            "next_steps": "Confirm with the dispatcher at Frankie Trucking regarding job assignments.. Ensure the caller has the correct contact information for their dispatcher.. Follow up with the caller if needed to ensure they are receiving messages in the future",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNf8fb855f16fa406aaec7257689cdb77c",
        },
    ],
    "GOLD SHORTS": [
        {
            "id": "369031558889",
            "date": "2026-05-11",
            "direction": "inbound",
            "duration_sec": 229,
            "contact": "Dany",
            "summary": "The caller is trying to access an application for Gold Shorts but cannot due to a missing account in the system. Marco Alvarez identifies that the caller's phone number was incorrectly entered in the system. The correct phone number was updated, allowing the caller to access the application. The caller worked with a different application previously and is now trying to use a new one",
            "next_steps": "Ensure the caller tests the application access with the updated phone number.. Confirm that the caller receives the verification message after the update.. Follow up with the caller if they encounter any further issues accessing the application",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN050c6cf5da53458181da584d633ff6cc",
        },
    ],
    "GURNEK TRANSPORT": [
        {
            "id": "369538692812",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 410,
            "contact": "Gurnek Transport",
            "summary": "Jill Bajenting from Tread contacted Gary to assist drivers with job acceptance. The drivers, Gurkurath and Ravinder, have limited English skills, prompting the need for assistance. Gurkurath was helped first to log in to the Tread app and successfully accessed his job. Ravinder was then called in and also successfully logged in and accessed his job. Previous issues with drivers not receiving dispatches were resolved",
            "next_steps": "Ensure both drivers are aware of their job details and can start their tasks.. Monitor the drivers' progress to confirm they are able to complete their jobs without further issues.. Follow up with the drivers after their shifts to gather feedback on the app's functionality",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNfb6c5ff1f6dd478ca306bc83ee073c64",
        },
        {
            "id": "369441984215",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 93,
            "contact": "unknown contact",
            "summary": "Jill Bajenting informs Navi that Gurkharat cannot see assigned tasks due to a job being assigned to a removed phone number. Navi suggests contacting a colleague in the office who manages the app for assistance with the issue. Navi provides the phone number of the colleague to Jill for follow-up",
            "next_steps": "Jill should call the colleague at the provided phone number (647-680-3807) to resolve the assignment issue.. Reassign the job to the correct phone number once the colleague is contacted",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNec578c1f01114d9581441e615f9902a5",
        },
    ],
    "H FIVE TRUCKING": [
        {
            "id": "369365498568",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 109,
            "contact": "Jaime Lopez",
            "summary": "Marco assists with adding Sam Houston as a driver for h five Trucking. Sam Houston is already an admin, which requires managing his role in the vendor account. The user initially faced issues updating the driver's role but successfully added it after troubleshooting. Marco reminds the user to assign the driver to a truck after adding the role",
            "next_steps": "Assign Sam Houston to a truck after updating his role to driver.. Confirm that all necessary equipment is assigned to him.. Check if there are any further issues with adding drivers in the future",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNacf3987780844256b3f3bd57d1706ce2",
        },
    ],
    "R.W. DUNTEMAN CO.": [
        {
            "id": "369267258072",
            "date": "2026-05-12",
            "direction": "outbound",
            "duration_sec": 1082,
            "contact": "Roland Dunteman",
            "summary": "Marco Alvarez followed up with Roland regarding dispatches and deployment status. Roland expressed concerns about falling behind on deployment but indicated progress on dispatching. Discussion about managing a single truck for multiple jobs and setting up orders for each job. Clarification on how to handle billing and settlements for vendor drivers, particularly time tracking during loading and unloading. Need for training vendors to use the app for accurate load and dump times. Marco suggested a meeting to go through settlement examples and ensure proper setup for invoicing. Roland intends to focus on vendor settlements and prepare for the upcoming meeting",
            "next_steps": "Schedule a follow-up meeting for Thursday at 2 PM to discuss settlements and invoicing.. Prepare examples of vendor settlements for the meeting.. Train vendors on using the app to input load and dump times accurately.. Check with Tim about the status of settlement exports for integration with Vista",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNedcff20661984d13971f041783c66dc4",
        },
        {
            "id": "369229197043",
            "date": "2026-05-12",
            "direction": "outbound",
            "duration_sec": 65,
            "contact": "Roland Dunteman",
            "summary": "Marco Alvarez from Tread called Roland at RW Dunham and Company to check in. Marco requested a callback from Roland when he has time",
            "next_steps": "Roland should return Marco's call at his earliest convenience",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNedcff20661984d13971f041783c66dc4",
        },
    ],
    "RONYX LOGISTICS LLC": [
        {
            "id": "369545468606",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 66,
            "contact": "Veronica Butanda",
            "summary": "Marco Alvarez called Veronica to follow up on requests for changes regarding Edgar and Juan dispatches. He offered to discuss options over the phone and provided his contact number for a callback",
            "next_steps": "Veronica should return Marco's call at (647) 977-3306.. Discuss the requested changes for Edgar and Juan dispatches with Marco.. Consider the options Marco will provide during the call",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNd0688fe70be044839bd4ec54cc1d2a67",
        },
        {
            "id": "369399849695",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 92,
            "contact": "Veronica Butanda",
            "summary": "Veronica from Ronix Transportation Logistics needs to speak with a salesperson about a new customer interested in software. Max, the previous salesperson, is not answering calls and is no longer with Tread. Veronica has referred another customer who ended up purchasing the software through a different sales representative due to Max's unavailability. Jill confirms she will inform Marco, another salesperson, to follow up with Veronica as soon as possible",
            "next_steps": "Jill will notify Marco about Veronica's request for a callback.. Marco should reach out to Veronica promptly to assist with the new customer inquiry.. Ensure that all sales representatives are updated about Max's departure and the need for timely communication with clients",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNd0688fe70be044839bd4ec54cc1d2a67",
        },
        {
            "id": "369383719624",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 237,
            "contact": "Veronica Butanda",
            "summary": "Veronica from Ronix Logistics seeks to restrict dispatchers from accessing each other's jobs. Juan Alvarado dispatches morning shifts, while Edgar DeDeo Ramos dispatches night shifts for the Domino Project. Veronica wants to ensure that each dispatcher can only manage their assigned shifts and not interfere with others. There are issues with Juan not following the protocol regarding assignments for drivers, particularly with the White River company. Only RAAJ is allowed to assign their own drivers due to past issues with unlicensed drivers",
            "next_steps": "Jill will check with her team about implementing access restrictions for dispatchers.. Jill will gather information on how to enforce the rules regarding driver assignments and communicate back to Veronica",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNd0688fe70be044839bd4ec54cc1d2a67",
        },
    ],
    "STATEWIDE MATERIALS": [
        {
            "id": "369576654522",
            "date": "2026-05-14",
            "direction": "inbound",
            "duration_sec": 271,
            "contact": "unknown contact",
            "summary": "Jill from Tread is assisting Ernest from Statewide regarding an issue with a job. Drivers are being kicked off the job unexpectedly, specifically for order number 847017. The job is for Westwood High School and is scheduled for today with 10 loads per driver. The current system configuration shows 10 drivers with one load each, causing the job to go into review after one load is completed. Jill needs to consult with her team to find a solution and will call Ernest back",
            "next_steps": "Jill will check with her team regarding the issue of drivers being kicked off the job.. Jill will call Ernest back with an update on the situation.. Ensure the job configuration is corrected to allow for 10 loads per driver",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN62d4f8bdddd24913a84776cbf56902e8",
        },
        {
            "id": "368706675426",
            "date": "2026-05-08",
            "direction": "outbound",
            "duration_sec": 14,
            "contact": "Statewide Materials",
            "summary": "Marco Alvarez is involved in a conversation regarding listening and professional knowledge. A voicemail message from Statewide Materials indicates their business hours are Monday to Friday, 8AM to 5PM",
            "next_steps": "Follow up with Marco Alvarez about the conversation.. If needed, call Statewide Materials during business hours for further inquiries",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNfe61961c8c724f8ea172b42c35429764",
        },
    ],
    "STRAIN TRUCKING": [
        {
            "id": "369087685359",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 269,
            "contact": "Juan Alvarado",
            "summary": "Marco Alvarez confirmed the change of the driver to Strain Trucking. The driver, Eric Cruz, was previously associated with Misty Blue but is now under Strain Trucking since Monday. The company name for the driver has been updated, but completed jobs cannot be retroactively changed to reflect this. Future communications should clearly specify to remove drivers from Misty Blue when transitioning to Strain Trucking",
            "next_steps": "Ensure all future messages specify to remove drivers from Misty Blue when they transition to Strain Trucking.. Verify that all relevant documentation reflects the change to Strain Trucking for Eric Cruz.. Monitor any pending jobs to ensure they are correctly associated with the new company name",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN9a47737985a743bcbbafa1c2b23b736a",
        },
    ],
    "T WALLACE TRUCKING LLC": [
        {
            "id": "369361942248",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 219,
            "contact": "Curtis",
            "summary": "Jill from TriNet called Curtis Hill to gather additional company information for account creation. Curtis confirmed the company name as 'T Wallace Trucking LLC' but it was not found in the system. Jill requested the contact number for the dispatcher, which Curtis provided as (317) 801-6592. Curtis confirmed the dispatcher’s name as T Wells, who is also the owner of the company. Jill will contact the dispatcher for further information and will send an SMS invite to Curtis once the account is created",
            "next_steps": "Jill to contact dispatcher T Wells for additional company information.. Create Curtis's account in the system once information is received.. Send an SMS invite to Curtis with login details after account creation",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CN23353cbaecfb48f89385f12fb9c4e6dd",
        },
    ],
    "TEXAS LIME": [
        {
            "id": "369301228234",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 61,
            "contact": "Sedric Surles",
            "summary": "Jill from Tread contacted Cedric regarding a job that was accidentally marked as completed. There is an option to restore the job by contacting the AccessLine company. Cedric needs to provide the order number to the dispatcher at Texas Lime company to restore the job",
            "next_steps": "Cedric will contact the dispatcher at Texas Lime company.. Cedric will provide the order number to restore the job",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN61a8d6f15475402f853065d085212bdd",
        },
        {
            "id": "369368792817",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 215,
            "contact": "Sedric Surles",
            "summary": "Jill from Credit is assisting Cedric from Texas Lime regarding an issue with Tread. Cedric accidentally canceled a load for tomorrow's job and needs to uncancel it and reassign the driver. Jill confirms the job status is marked as completed, which complicates the process of uncanceling it. Jill will check with her team to see if there is a way to reactivate the job or if Cedric needs to request a replacement job from Texas Lime",
            "next_steps": "Jill will consult her team about the possibility of reactivating the canceled job.. If reactivation is not possible, Jill will inform Cedric that he may need to request a replacement job from Texas Lime.. Jill will follow up with Cedric once she has more information",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN61a8d6f15475402f853065d085212bdd",
        },
    ],
    "TOMPKINS BROS": [
        {
            "id": "369024465601",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 60,
            "contact": "Tompkins Bros",
            "summary": "A voicemail from SJ Masonry indicates they are unavailable to take calls and encourages callers to leave a message. Shay Bonifacio is calling Sean to request additional company information for a program",
            "next_steps": "Sean should return Shay's call to provide the requested company information.. Shay should follow up if she does not hear back from Sean in a timely manner",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN42e470cc1cb640ccaf39f8b4d8cda9a8",
        },
    ],
    "TRACON": [
        {
            "id": "369413177058",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 330,
            "contact": "Jaymes Pendergast",
            "summary": "Marco assists a caller who mistakenly entered 'TRENCON' instead of 'TRACON' for an owner operator. The caller corrected the name in one place but needed help with the email and company name. Marco explains that changes to the visible name do not automatically update the actual account information. The correct name and email 'trevor@trekconservices' are confirmed and updated successfully. The caller expresses appreciation for Marco's assistance",
            "next_steps": "Ensure all instances of 'TRENCON' are updated to 'TRACON' in the system.. Verify that the email address is correctly updated to 'trevor@trekconservices'.. Consider implementing a system to track daily call volumes as discussed",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN46717753be534cd69358944a1a5e703b",
        },
    ],
    "TRANSWORLD TRUCKING": [
        {
            "id": "369371276990",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 161,
            "contact": "Todd Silva",
            "summary": "Marco and Todd experienced a call issue with crackling sounds. Todd needs to reenter truck numbers and confirm drivers are already created. They discuss creating a new equipment entry for a semi truck trailer. Todd is advised to send a list of duplicate units via email after completing his task",
            "next_steps": "Todd will create truck numbers and assign them to the existing drivers.. Todd will create a new equipment entry for the semi truck trailer.. Todd will send an email with a list of duplicate units after completing the task",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNaf471b4604db4b73ba1710c96614297b",
        },
        {
            "id": "369416838846",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 330,
            "contact": "Todd Silva",
            "summary": "Marco Alvarez explains how to manage unit numbers in the system for TransWorld. Todd from TransWorld is confused about editing equipment details. Marco clarifies that Todd cannot edit equipment belonging to owner operators. To assign equipment to drivers, Todd needs to create new entries for the trucks under his company account. Marco advises that duplicates may occur, but they can be removed from the vendor's account",
            "next_steps": "Todd needs to create new equipment entries under TransWorld's account.. Ensure all trucks are assigned to TransWorld and not individual drivers.. Contact support if duplicates appear to have them removed from the vendor's account",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNaf471b4604db4b73ba1710c96614297b",
        },
        {
            "id": "369410350787",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 75,
            "contact": "Todd Silva",
            "summary": "Marco Alvarez called Todd Selma from Tread to discuss options for setting up units for Transwidth. Marco left a message requesting Todd to call him back at a specific number",
            "next_steps": "Todd should return Marco's call at (647) 977-3306.. Marco should prepare information about the unit options for the follow-up conversation",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNaf471b4604db4b73ba1710c96614297b",
        },
    ],
    "UNCLASSIFIED": [
        {
            "id": "369412916946",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 72,
            "contact": "unknown contact",
            "summary": "Marco and Ed discuss an integration issue with their IT teams. Ed confirms that data is pushing correctly on their side. Marco requests Ed to send screenshots to support@threat.io for further investigation. Marco will share the information with his team to look into the ticket created",
            "next_steps": "Ed to send the screenshots to support@threat.io.. Marco to share the information with his team for further investigation",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNcc671a1bac254263b9406c0344c342ae",
        },
        {
            "id": "369095551715",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 69,
            "contact": "unknown contact",
            "summary": "Marco Alvarez confirmed the transfer of work from the caller to Juan Carlos Gruzón. The caller initially had a job but needed to pass it on due to a driver being left without work. Marco will notify Juan Carlos Gruzón about the job assignment",
            "next_steps": "Marco to inform Juan Carlos Gruzón about the job transfer.. Caller to ensure Juan Carlos is prepared for the job assignment",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNf72b10f32b214429afe8e9912f3c1ce2",
        },
        {
            "id": "369118103261",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 261,
            "contact": "unknown contact",
            "summary": "Marco Alvarez of Trade returned a call to discuss adding a new driver. The caller wants to add Edgar Galindo as a driver for night shifts. Edgar has the same phone number but needs to download the app again after changing phones. Felipe Munera is to be removed from the list as he no longer works with the caller. The caller confirmed that Hector Mercado and Jonathan Ruiz are still active drivers. Juan Carlos Sosa is to remain on the list, while Juan Gacharna is to be removed. Elmer Estrada is not on the current driver list",
            "next_steps": "Add Edgar Galindo to the driver list with phone number 7025101225.. Remove Felipe Munera from the driver list.. Confirm that Hector Mercado and Jonathan Ruiz remain on the driver list.. Keep Juan Carlos Sosa on the list and remove Juan Gacharna.. Check if Elmer Estrada needs to be added or if he is not required",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN46d41d95bf0f4824b1ce47cad1ab1da8",
        },
        {
            "id": "369023273659",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 76,
            "contact": "Abdul",
            "summary": "Charlie from the credit dispatching program called Abdul for additional company information to create a credit account. Sherry from Credit Suites collection program also called Abdul for initial company information to gauge a credit account. Abdul was not available to take the calls",
            "next_steps": "Follow up with Abdul to ensure he received the messages.. Provide the required company information to both Charlie and Sherry.. Schedule a time for Abdul to return the calls",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN10e457f5697046b9a255bc70d0873438",
        },
    ],
    "UNKNOWN COMPANY (AMARJIT)": [
        {
            "id": "369567744744",
            "date": "2026-05-14",
            "direction": "inbound",
            "duration_sec": 243,
            "contact": "Amarjit",
            "summary": "Jill from Tread helps a customer with adding a driver to their account. The driver needs to log in using their own phone number, which requires adding their phone number to the account. The customer provides the driver's phone number and name (Gary) to Jill. Jill confirms the truck number and successfully adds the driver to the account, allowing him to log in",
            "next_steps": "Confirm that Gary received the SMS invitation to log in to Tread.. Verify that Gary can successfully log in using his phone number.. Ensure that the truck number associated with Gary's account is correct",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN0c446e92591c467cbb5b7a398eb40e36",
        },
        {
            "id": "369442549472",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 27,
            "contact": "Amarjit",
            "summary": "The call was forwarded to voicemail. The person being called is not available",
            "next_steps": "Try calling again later.. Send a text message to follow up",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CN0c446e92591c467cbb5b7a398eb40e36",
        },
    ],
    "UNKNOWN COMPANY (CHRIS DUSENBERRY)": [
        {
            "id": "369218540229",
            "date": "2026-05-12",
            "direction": "outbound",
            "duration_sec": 502,
            "contact": "Chris Dusenberry",
            "summary": "Marco and the caller discussed a project named I70 that involves two separate orders: milling and asphalt. The caller faced issues updating the phase name and code for the new order, which eventually resolved after multiple attempts. The phase name and code for asphalt were successfully added to the project after troubleshooting together. The caller inquired about real-time scale data integration with their asphalt operations, but Marco did not have detailed information on that. The caller plans to follow up with Tim for more information about the real-time data integration",
            "next_steps": "The caller should reach out to Tim again for information on the real-time scale data integration.. Marco will follow up on the integration details and share any insights with the caller during their next conversation",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN4b2e6ca010f14f03a0f0837b794ca567",
        },
        {
            "id": "369203999445",
            "date": "2026-05-12",
            "direction": "inbound",
            "duration_sec": 14,
            "contact": "Chris Dusenberry",
            "summary": "Marco Alvarez initiates a call with Mark. Mark confirms he is present on the call. Chris is also involved in the conversation",
            "next_steps": "Ensure all participants can hear each other clearly.. Proceed with the agenda of the call",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN4b2e6ca010f14f03a0f0837b794ca567",
        },
    ],
    "UNKNOWN COMPANY (DAVID RAUL)": [
        {
            "id": "369095561923",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 218,
            "contact": "David",
            "summary": "Marco Alvarez guides David through opening the thread application. David successfully enters his phone number and signs in. Marco instructs David to allow location access and set notification preferences. David selects push and SMS notifications as instructed. The setup is completed successfully",
            "next_steps": "Ensure David has access to the thread application for future use.. Confirm that notification settings are functioning as expected.. Follow up with David to address any further questions or issues",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNb35419c3e45d496a9c8bcc4c58e66571",
        },
        {
            "id": "369059573467",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 41,
            "contact": "David",
            "summary": "Marco Alvarez from Tread called David and left a message. The call was forwarded to an automated voice messaging system. Marco requested David to let him know when he is available for a callback. Marco mentioned that their phone is currently after hours and provided a text option for David",
            "next_steps": "David should respond to Marco's message indicating his availability for a callback.. David can send a text message to the number provided if he prefers that method.. Marco should check for David's response and schedule a callback accordingly",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNb35419c3e45d496a9c8bcc4c58e66571",
        },
    ],
    "UNKNOWN COMPANY (DAVID WHITESELL)": [
        {
            "id": "369023326953",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 36,
            "contact": "David",
            "summary": "David is currently busy in the field and unable to take calls. Cherry Bonifacio is trying to reach David for additional company information related to credit. The call ended with an invalid entry message",
            "next_steps": "David should check his voicemail for Cherry's message.. Cherry should attempt to call David again or send an email for the information needed",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CNbe066324274547eabc99064716920821",
        },
    ],
    "UNKNOWN COMPANY (DAYANA)": [
        {
            "id": "369300811496",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 564,
            "contact": "Dayana",
            "summary": "Diana is trying to add SMI numbers for trucks on the new Tread system but is encountering issues. SMI numbers were previously added to the license number in the old system. Marco informs Diana that some trucks are owned by others, preventing her from adding the SMI numbers herself. Marco suggests that the SMI numbers need to be added on their end for trucks owned by others. Diana needs the SMI numbers to be included in the OmniReport for store mining. Marco will check if the equipment ID can be combined with the SMI number for reporting purposes. Diana agrees to manually send the SMI numbers until a solution is found",
            "next_steps": "Diana will send Marco an email detailing which reports require the SMI numbers.. Marco will discuss with the team about adding SMI numbers to the trucks owned by others.. Diana will continue to manually send SMI numbers in the mornings until resolved",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN5dae8b8a369b4d74bd64c7edf3bc9e96",
        },
        {
            "id": "368975651567",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 386,
            "contact": "Dayana",
            "summary": "The caller is experiencing issues dispatching three trucks due to them not appearing in the system. Marco checks the truck numbers and driver names provided by the caller. It is revealed that some drivers are currently working for other companies, affecting their visibility in the dispatch system. Marco explains that drivers can work for multiple companies but may not appear if they are currently assigned elsewhere. The caller successfully retrieves the visibility of the drivers after Marco's assistance",
            "next_steps": "Verify the status of each driver to ensure they are available for dispatch.. Communicate with drivers about their availability when working for multiple companies.. Ensure the dispatch system is updated to reflect the correct status of drivers working for more than one company",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN5dae8b8a369b4d74bd64c7edf3bc9e96",
        },
    ],
    "UNKNOWN COMPANY (GARTH SCOTT)": [
        {
            "id": "369372383955",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 491,
            "contact": "Garth Scott",
            "summary": "The caller had trouble accessing their account after trying to change their phone number. Marco helped the caller revert to their original phone number (516) 424-8882. The caller was initially logged out and could not see their account after the change. Marco confirmed the driver's name is Marlon Combs and added him to the account. The caller successfully logged back into their account after the phone number was updated",
            "next_steps": "Ensure the caller verifies their account access with the updated phone number.. Confirm that Marlon Combs is correctly added to the system as a driver.. Check on the truck number 72704 and ensure all details are accurate.. Follow up with the caller if they encounter any further issues",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CN06d77939a1854ff99698b95aeb48c01f",
        },
    ],
    "UNKNOWN COMPANY (GILBERTO)": [
        {
            "id": "368666127086",
            "date": "2026-05-08",
            "direction": "outbound",
            "duration_sec": 34,
            "contact": "unknown contact",
            "summary": "Marco Alvarez is responding to a message from April 26. Gilberto confirms that the issue has been resolved. Both parties exchange pleasantries and wish each other a good weekend",
            "next_steps": "No specific next steps identified; communication issue resolved",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNa688aae42e5848229ba8257793717fe4",
        },
    ],
    "UNKNOWN COMPANY (HECTOR ROJAS)": [
        {
            "id": "369245624001",
            "date": "2026-05-12",
            "direction": "outbound",
            "duration_sec": 55,
            "contact": "Rojas, Hector",
            "summary": "Marco Alvarez from THRED is following up with Hector regarding some questions he had about the dispatching program. Marco encourages Hector to reach out anytime at the provided phone number",
            "next_steps": "Hector should return Marco's call to discuss his questions about the dispatching program.. Hector should prepare any specific questions he has before the call",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN8296696c22ee4ca982ce4b1874656da5",
        },
        {
            "id": "368721152723",
            "date": "2026-05-09",
            "direction": "outbound",
            "duration_sec": 8,
            "contact": "Rojas, Hector",
            "summary": "The call was forwarded to voicemail",
            "next_steps": "Check voicemail for any messages left by the caller",
            "quo_url": "https://my.quo.com/inbox/PNYHFsiYxL/c/CN9f2597cfdd9d45a7997ea03b995ccd4d",
        },
    ],
    "UNKNOWN COMPANY (JALIL GRESHAM)": [
        {
            "id": "369023344336",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 231,
            "contact": "Jalil",
            "summary": "Cherry Bonifacio from the dispatching program called to gather additional information for creating a Tread account. The caller provided the name and phone number of the person who referred them, Omar Kiah. The caller's name was confirmed as Jalil Gresham, and he is a driver, not an owner-operator. Cherry created the account and mentioned that an SMS invite with login instructions would be sent to Jalil. Jalil acknowledged that he would check for the SMS invite and proceed with the account setup",
            "next_steps": "Confirm that the SMS invite was received by Jalil Gresham.. Ensure Jalil successfully logs into the Tread app and completes any additional account setup requirements.. Follow up with Jalil if he encounters any issues during the login process",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNce384ea971024c3caa2bafe51dc40959",
        },
        {
            "id": "368962804468",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 53,
            "contact": "Jalil",
            "summary": "Carrie Bonifacio is calling to request additional company information for an account. The person Carrie is trying to reach is currently unavailable",
            "next_steps": "Wait for a callback from the person Carrie is trying to reach.. Consider leaving a detailed message with the required company information.. Check if there is an alternative contact for the account",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNce384ea971024c3caa2bafe51dc40959",
        },
    ],
    "UNKNOWN COMPANY (JASHAN)": [
        {
            "id": "369363268283",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 601,
            "contact": "unknown contact",
            "summary": "Marco from Thread assists Jashan with account issues. Jashan is unable to log in as a driver due to an inactive account. Jashan created a new account because the original was inactive. Marco clarifies that Jashan needs to be assigned as a driver on the existing account instead of creating a new one. Jashan successfully logs into the driver account after troubleshooting steps with Marco. Marco advises Jashan to inform his team to dispatch the correct account going forward. At the end of the day, Jashan needs to call back to delete the extra account",
            "next_steps": "Jashan should inform his team to dispatch the correct driver account.. Jashan needs to ensure that all permissions for location tracking are enabled in the app.. At the end of the day, Jashan should call Marco back to delete the extra account.. Jashan should discuss the timing and billing adjustments with his dispatch team",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CNa49f92f621f34d4fbbfb30235acef5dc",
        },
    ],
    "UNKNOWN COMPANY (KRYSTAL QUADE)": [
        {
            "id": "368715965134",
            "date": "2026-05-09",
            "direction": "outbound",
            "duration_sec": 206,
            "contact": "Krystal Quade",
            "summary": "Marco Alvarez informs that drivers need to be removed from 'rock and roll' and added for Monday but cannot be moved if they have dispatches. The drivers in question are Isiah Jefferson and Craig Miller. Craig is still active for the day, so he cannot be removed until he is inactive. Isiah can be moved if he is done for the day and unassigned for Monday. The conversation ends with confirmation that the necessary changes have been made",
            "next_steps": "Confirm that Isiah Jefferson is inactive and unassign him for Monday.. Ensure Craig Miller is marked as inactive before trying to remove him from dispatch.. Verify that the changes have been successfully implemented for both drivers",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNca32a7d5a1584e129199abae63b138d9",
        },
    ],
    "UNKNOWN COMPANY (LUPE ESCARENO)": [
        {
            "id": "369268240077",
            "date": "2026-05-12",
            "direction": "inbound",
            "duration_sec": 127,
            "contact": "Lupe Escareno",
            "summary": "Marco and Lupe discussed an issue related to admin settings affecting data integration. Lupe questioned whether all data needed to be pulled for integration and if customization was possible. Marco suggested sending an email with a screenshot to Tim or Samir for further clarification. They agreed that only necessary truck information should be collected for display. Lupe plans to send an email including the other company for additional input",
            "next_steps": "Lupe will send an email to Tim and Samir including the screenshot and questions about the data integration.. Include the other company in the email for their insights on the data being pulled.. Await responses from Tim, Samir, and the other company regarding the integration process",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN5730d0ccc21d4cf283aeec460d7afb54",
        },
        {
            "id": "369270506178",
            "date": "2026-05-12",
            "direction": "outbound",
            "duration_sec": 218,
            "contact": "Lupe Escareno",
            "summary": "Marco and Lupe discussed an issue with Frankie accessing Motive during a Zoom call. Frankie was able to log in but was directed straight to Motive without seeing the expected permissions screen. Lupe plans to forward a link to Frankie to help him access Motive correctly. They discussed the need for Frankie to have administrative rights to access all features of Motive. Lupe will contact Frankie to advise him to use an account with full administrative rights",
            "next_steps": "Lupe will forward the link to Frankie.. Lupe will call Frankie to discuss the administrative rights needed for Motive.. Frankie should attempt to log in again using an account with full administrative rights",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN5730d0ccc21d4cf283aeec460d7afb54",
        },
    ],
    "UNKNOWN COMPANY (NATE GEORGE)": [
        {
            "id": "369556337374",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 145,
            "contact": "Nate George",
            "summary": "Marco explains the idling icon feature and its purpose related to truck speed. The idling icon indicates when the truck is moving under a certain speed, not just when it has been idling for a set time. There are issues with the icon not updating in real time, requiring a page reload, which the team is addressing. The feature is useful for customers to understand truck idling status. Nate appreciates the information and plans to relay it",
            "next_steps": "Marco's team will work on fixing the real-time update issue for the idling icon.. Nate will relay the information about the idling icon feature to relevant stakeholders",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CNa1c9c1ba76254c78ab9b9210e4a58eab",
        },
        {
            "id": "369410375379",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 35,
            "contact": "Nate George",
            "summary": "Marco Alvarez left a voicemail for Nathan George regarding a matter related to the idling icon. Marco requested Nathan to call him back when he has a moment",
            "next_steps": "Nathan should return Marco's call regarding the idling icon.. Review any relevant information about the idling icon before the call",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CNa1c9c1ba76254c78ab9b9210e4a58eab",
        },
        {
            "id": "369359751891",
            "date": "2026-05-13",
            "direction": "inbound",
            "duration_sec": 404,
            "contact": "Nate George",
            "summary": "Nate contacted Marco regarding issues with the dispatch board showing idling indicators for drivers who are actively moving. Marco explained that the idling indicator may not be functioning correctly and agreed to investigate further. They discussed specific drivers and the nature of their work, confirming that the drivers are not idling but rather loading and unloading frequently. Nate suggested that the idling threshold be adjusted from five minutes to twenty to twenty-five minutes to better reflect the operational reality. Marco agreed to report the issue and bring up the suggestion for a longer idling time with the team",
            "next_steps": "Marco will flag the idling indicator issue with the team for further investigation.. Marco will propose adjusting the idling threshold to twenty to twenty-five minutes to accommodate loading and unloading times.. Marco will follow up with Nate on the outcomes of the discussions regarding the idling indicators",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CNa1c9c1ba76254c78ab9b9210e4a58eab",
        },
        {
            "id": "369031443182",
            "date": "2026-05-11",
            "direction": "inbound",
            "duration_sec": 155,
            "contact": "Nate George",
            "summary": "Nathan called Jill from Tred regarding a driver named Demond who was logged in but not showing active status in the app. Jill identified that Demond had not pressed the start button for his job, which is why there was no communication of driving status. Nathan confirmed that Demond's clock was running, indicating he was on duty but had not started the order. Jill suggested that Nathan guide Demond to back out of the app and then re-enter to start the order. Jill offered to send Nathan a screenshot of Demond's job for reference",
            "next_steps": "Nathan will instruct Demond to back out of the app and then start the order.. Jill will send Nathan a screenshot of Demond's job for reference",
            "quo_url": "https://my.quo.com/inbox/PNuJijrDpE/c/CNa1c9c1ba76254c78ab9b9210e4a58eab",
        },
    ],
    "UNKNOWN COMPANY (RACHEL)": [
        {
            "id": "369455695581",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 207,
            "contact": "Rachel",
            "summary": "Jill from the program called Rachel to gather information for setting up an account. Rachel confirmed she is both the lender and driver for Jones, Kettle and Moore, LLC. Jill inquired about the dispatcher company that sends Rachel dispatches. Rachel mentioned running with a company called Larry Young but noted they are not on the app. Jill explained that Tread requires users to be under a company that is already in the app to receive job dispatches. Rachel was asked to check if her dispatcher is on Tread and provide their details if available",
            "next_steps": "Rachel should verify if Larry Young or any other dispatcher is registered on Tread.. If Rachel's dispatcher is on Tread, she should provide their company name and phone number to Jill.. Jill will check the provided details to assist Rachel with her account setup",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CN1c844415d416440593a95b23c93cbea3",
        },
    ],
    "UNKNOWN COMPANY (ROHAN WILSON)": [
        {
            "id": "368975886073",
            "date": "2026-05-11",
            "direction": "inbound",
            "duration_sec": 301,
            "contact": "Rohan Wilson",
            "summary": "Jill from Tread assists a caller who is trying to log in. The caller initially provides an incorrect email address but successfully logs in using their phone number. The caller wants to add a driver named Kimari Harrison to their account. Jill confirms the driver's phone number and ensures the driver will work exclusively for the caller's company. Jill successfully adds the driver to the account and informs the caller that an SMS invite has been sent to the driver for logging in",
            "next_steps": "Confirm that the driver received the SMS invite and can log in successfully.. Ensure that the driver is visible in the dispatch system for the caller.. Follow up with the caller if they have any further questions or issues",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNcc0dcf28d2194c35a4a27aeb9b540634",
        },
    ],
    "UNKNOWN COMPANY (SENEIL)": [
        {
            "id": "369025207001",
            "date": "2026-05-11",
            "direction": "outbound",
            "duration_sec": 252,
            "contact": "Seneil",
            "summary": "Cherry Bonifacio from TriNet called to gather additional company information to locate a TriNet account. The call had some communication issues due to a strong accent and poor audio quality. The caller requested the name and phone number of the person associated with the Tread app registration. The recipient, identified as a driver, provided the name and number of their employer, Susan Myers. Cherry confirmed that the recipient is only a driver and successfully created their account, promising an SMS invite for login",
            "next_steps": "Ensure the recipient receives the SMS invite to log in to their account.. Follow up with the recipient if they do not receive the SMS invite within a specified timeframe.. Consider addressing communication issues for future calls to improve clarity",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CN7fbf1db3d8d547cba8230ca186953d2b",
        },
    ],
    "UNKNOWN COMPANY (SID SPEAR)": [
        {
            "id": "369587945169",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 242,
            "contact": "Sid Spear",
            "summary": "Marco and Zed discuss the need to manage truck numbers and drivers in their system. Zed is trying to match truck numbers and is facing issues with adding new trucks and identifying truck types. Marco explains that if a truck number isn't selected when adding a driver, the system defaults to 'my truck'. They plan to have a meeting at 03:00 to go through the truck number issue in detail. Zed expresses concern about spending time cleaning up the system without a clear resolution",
            "next_steps": "Schedule and attend the meeting at 03:00 to address the truck number and driver management issues.. Review the process for adding drivers and truck numbers to ensure clarity on truck types.. Investigate why certain truck types are not appearing in the system when adding new drivers",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN6f1237651ab94b999fb57c3da327739f",
        },
        {
            "id": "369458093779",
            "date": "2026-05-14",
            "direction": "outbound",
            "duration_sec": 69,
            "contact": "Sid Spear",
            "summary": "Sid Spear is currently out of the office from May 4 to May 11. Marco Alvarez from Thread has sent Sid a link regarding a list Sid had questions about. Marco is waiting for Sid to respond so they can reconnect",
            "next_steps": "Marco should follow up with Sid after May 11 if he does not receive a response.. Sid should check his messages periodically and respond to Marco regarding the link sent",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN6f1237651ab94b999fb57c3da327739f",
        },
        {
            "id": "369231188709",
            "date": "2026-05-12",
            "direction": "inbound",
            "duration_sec": 523,
            "contact": "Sid Spear",
            "summary": "The conversation involved troubleshooting issues with a chat application. Marco provided guidance on accessing the vendor and driver pages for data management. The user learned how to export a complete list of drivers and vendors, as well as how to deactivate drivers in the system. Discussion on the importance of matching truck numbers with driver information. Marco instructed the user on how to view and edit license plate information in the equipment settings",
            "next_steps": "Access the vendor page to export all driver and vendor data.. Match truck numbers with the corresponding driver names and phone numbers.. Deactivate any drivers who are no longer with the company.. Check and verify the accuracy of license plate numbers in the equipment settings.. Add any missing license plate numbers directly in the system",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN6f1237651ab94b999fb57c3da327739f",
        },
        {
            "id": "369270191834",
            "date": "2026-05-12",
            "direction": "outbound",
            "duration_sec": 52,
            "contact": "Sid Spear",
            "summary": "Sid Spiro is out of the office from May 4 to May 11 and will check messages periodically. Marco Alvarez is following up on a previous message and hopes to connect with Sid",
            "next_steps": "Marco should wait for Sid to return and check his messages.. If no response from Sid by May 11, Marco should reach out again to follow up",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN6f1237651ab94b999fb57c3da327739f",
        },
    ],
    "UNKNOWN COMPANY (TRANSFROT FL)": [
        {
            "id": "369274344147",
            "date": "2026-05-12",
            "direction": "inbound",
            "duration_sec": 294,
            "contact": "unknown contact",
            "summary": "Caller is a company owner from TransFrot, Florida, having issues with a job assigned on the 11th. The job in question is named VOGCPH 2 import Mayacra, which should have 5 loads but the system was not allowing ticket uploads. Marco assists the caller by confirming the number of loads and guiding them to refresh the application to see the correct number of loads. After refreshing, the caller is able to see the 5 loads and is grateful for the assistance",
            "next_steps": "Verify if the system issues with ticket uploads are resolved for future jobs.. Ensure the application is user-friendly for drivers to avoid similar issues.. Follow up with the caller to confirm their satisfaction with the resolution",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CNc8642cebc42d4eebb035e0c65e312d38",
        },
    ],
    "VERONICS": [
        {
            "id": "369033981640",
            "date": "2026-05-11",
            "direction": "inbound",
            "duration_sec": 201,
            "contact": "Edgar Daniel Ramos",
            "summary": "Daniel from Veronics called Marco at Treat for help with signing out of a tablet. Daniel's tablet was not allowing him to sign out, keeping the previous user's account active. Marco identified the issue and suggested clearing the cookies in the browser. Daniel confirmed he was using an Apple tablet and asked for instructions on how to clear cookies. After following Marco's instructions, Daniel successfully signed out and was able to log in with his account",
            "next_steps": "Ensure all users are aware of the cookie clearing solution for sign out issues.. Consider creating a simple guide on how to clear cookies on different devices for future reference.. Follow up with Daniel to confirm that the issue is fully resolved and he can access his account without further problems",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN3fa7a36d78f44d40b4de2c349ed14159",
        },
    ],
    "VOLKER STEVIN CONTRACTING": [
        {
            "id": "369546409673",
            "date": "2026-05-14",
            "direction": "inbound",
            "duration_sec": 88,
            "contact": "Adam Kolozetti",
            "summary": "Gemma from Volker reached out to Sameer to schedule a meeting. Sameer is available to meet at the Sandman hotel. They agreed to meet soon to clarify details needed for upstream processes. Sameer will notify the front desk to meet Gemma",
            "next_steps": "Sameer will head to the Sandman hotel to meet Gemma.. Sameer will inform the front desk that he is there to see Gemma.. Prepare any necessary documents or forms needed for the meeting",
            "quo_url": "https://my.quo.com/inbox/PNCB7meEoH/c/CN597552c2318c4a1f82d97255449b1c3d",
        },
    ],
    "WHITE RIVER HAULING": [
        {
            "id": "369378364104",
            "date": "2026-05-13",
            "direction": "outbound",
            "duration_sec": 115,
            "contact": "Antoinette",
            "summary": "Jill from Tread contacted Antoinette Wells regarding a driver named Curtis Hill. Curtis Hill registered under the incorrect company name, T Wells Trucking LLC. Antoinette confirmed that the correct company name is White River Hauling. Jill will update the records to reflect the correct company name for Curtis Hill",
            "next_steps": "Update Curtis Hill's registration to White River Hauling in the Tread system.. Confirm the update with Antoinette Wells once completed",
            "quo_url": "https://my.quo.com/inbox/PNkaCo2IXj/c/CN68fb48c77d0842cf9da27e91d7a79133",
        },
    ],
    "GULFSHORE TRUCKING LLC": [
        {
            "id": "370044182217",
            "date": "2026-05-18",
            "direction": "outbound",
            "duration_sec": 215,
            "contact": "Diana",
            "summary": "Marco called Diana from Gulf Shore Trucking to clarify a customer charge issue. Diana explained the problem was due to a customer name not recognized at the order level. Marco identified that the charge needed to be updated at the project level, not the order level. Diana confirmed she would inform Alfred to update the project with the correct customer name (Welch Tennis). Charge successfully updated.",
            "next_steps": "Alfred to update the project with the correct customer name. Verify updates are reflected in future orders.",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CNf0239fb606484376bd03d03bc29ffc69",
        },
    ],
    "ROCK ON TRUCKS": [
        {
            "id": "370169488093",
            "date": "2026-05-19",
            "direction": "outbound",
            "duration_sec": 527,
            "contact": "Krystal Quade",
            "summary": "Marco returned Crystal's urgent call about fuel surcharge update errors. Crystal is having trouble submitting changes in the project management system. Marco clarified business hours, offered to help, and sent Crystal an email with a screen sharing link to troubleshoot the submission issue together.",
            "next_steps": "Crystal to check email for screen sharing link from Marco. Crystal and Marco to conduct a screen share session to diagnose fuel surcharge submission errors.",
            "quo_url": "https://my.quo.com/inbox/PNYHFsiYxL/c/CN6c6b6ade05e94d128140c20a41c24118",
        },
        {
            "id": "370134297321",
            "date": "2026-05-19",
            "direction": "outbound",
            "duration_sec": 2055,
            "contact": "Krystal Quade",
            "summary": "Extended screen share troubleshooting with Crystal. Crystal has 144 jobs requiring fuel surcharge and internal note changes but is hitting submission errors. Team identified that a recent system update is causing duplicate add-on issues. Engineering fix expected soon. Marco advised Crystal to either wait for the release (reload when prompted) or create new add-ons as a temporary workaround.",
            "next_steps": "Monitor for engineering fix release and reload system when prompted. If fix doesn't resolve, create new add-ons for fuel surcharges as workaround. Continue making changes while tracking errors.",
            "quo_url": "https://my.quo.com/inbox/PNYHFsiYxL/c/CN6c6b6ade05e94d128140c20a41c24118",
        },
    ],
    "MMC MATERIALS INC": [
        {
            "id": "369717758695",
            "date": "2026-05-15",
            "direction": "inbound",
            "duration_sec": 154,
            "contact": "Michael Weldon",
            "summary": "Marco Alvarez called Michael from MMC regarding project setup. Marco confirmed he sent an email prior to the call for context. Michael asked about customer usage of specific products for projects. Marco offered to share his screen and sent a Google Meet link to discuss further.",
            "next_steps": "Marco to prepare documents/visuals for the meeting. Both to join Google Meet for detailed project setup discussion",
            "quo_url": "https://my.quo.com/inbox/PN3x1rCudr/c/CN8b65fd63584640d29912073d103fe2d8",
        },
    ],
}
